version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.2
    - 1.440.4
    - 1.441.0
    - 1.446.0
    - 1.448.0
    - 1.451.0
    - 1.452.0
    - 1.454.0
    - 1.456.0
    - 1.457.0
    - 1.458.0
    - 1.459.0
    - 1.460.0
    - 1.464.0
    - 1.467.0
    - 1.472.0
    - 1.477.0
    - 1.479.0
    - 1.483.0
    - 1.487.0
    - 1.490.0
    - 1.500.0
    - 1.503.0
    - 1.506.0
    - 1.509.0
    - 1.512.0
    - 1.514.0
    - 1.521.0
    - 1.523.0
    - 1.526.0
    - 1.529.0
    - 1.530.0
    - 1.531.0
    - 1.535.0
    - 1.542.0
    - 1.554.0
    - 1.563.0
    - 1.565.0
    - 1.567.0
    - 1.571.0
  - dependency-name: firebase
    versions:
    - 8.2.4
    - 8.2.5
    - 8.2.8
    - 8.3.3
  - dependency-name: gatsby-image
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 3.1.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.1
    - 2.32.10
    - 2.32.11
    - 2.32.4
    - 2.32.7
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.1
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.3
    - 2.13.4
